project:
  type: website 

website:
  title: "UQRUG"   
  image: "images/uqrug.png"
  open-graph:
    image: "images/uqrug_og.png"
    description: "The University of Queensland R Users Group"
  # twitter-card: 
  #   image: "images/uqrug_twitter.png"
  favicon: "images/uqrug_fav.png"  
  description: "UQRUG is a gathering for R users of all skills, to help each other solve problems, to share resources and tips, and to simply hang out with a nice community."
  navbar: 
    logo: "images/uqrug.png" 
    background: "#48206c"  
    foreground: "white" 
    right: 
      - text: Home
        href: index.qmd
      - events.qmd 
      - text: Notes
        href: pastmeetings.qmd
      - text: Community
        href: community.qmd
      - code_of_conduct.qmd
    tools:
      - icon: github
        href: https://github.com/UQRUG/uqrug_website
        aria-label: github
      # - icon: twitter
      #   href: https://twitter.com/UQ_RUG
      #   aria-label: Twitter 
      - icon: file-earmark-text
        href: https://pad.education/p/uqrug
        aria-label: Collaborative Document
      - icon: youtube
        href: https://www.youtube.com/@UQRUG
    
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual
 
execute: 
  freeze: auto
