---
title: "Community Groups"
 
about:
  template: marquee 
  links:
    - icon: hexagon-fill
      text: R Workshops
      href: https://web.library.uq.edu.au/library-services/training#keyword=Rstudio
    - icon: twitter
      text: Twitter
      href: https://twitter.com/UQ_RUG
    - icon: file-earmark-text
      href: https://frama.link/uqrug
      text: Collaborative Document
    - icon: github
      text: Github
      href: https://github.com/uqlibrary/technology-training
    - icon: chat-right
      text: UQ Chat
      href: https://chat.uq.edu.au/element/#/room/#uqrug:chat.uq.edu.au
    - icon: globe
      text: Created with quarto
      href: https://brisbane-geocommunity.netlify.app/posts/build-blog-w-quarto/
---

## Hacky Hour UQ

For UQ researchers to get support with research-related technical issues.

**When**: Weekly on Tuesdays, 3pm--4pm (AEST)

**Where**: Online. For Zoom meeting details please email rcc-support\@uq.edu.au

**More Details**: The [RCC Hacky Hour UQ website](https://rcc.uq.edu.au/meetups#hacky-hour)

## UQ GeoSpatial Analysis Community of Practice

A monthly geospatial skill sharing tutorial sessions where a member of the community shares their skills, experiences and tricks in a friendly and inclusive environment.

**When**: The last Thursday of the month, 2:30pm--4:30pm (AEST)

**Where**: Online. For meeting details please email Mitch at mitchel.rudge\@uq.edu.au

**More Details**: The [UQ GeoSpatial Analysis Community website](https://geospatial-community.netlify.app/)

## QUT/UQ Office Hours

For Australian researchers working with linguistics, text analytics, digital and computational methods, social media and web archives to bring their technical questions, research problems and rough ideas and get advice and feedback.

**When**: Fortnightly on Tuesdays, 2pm--3pm (**AEDT**).

**Where**: Online. For Zoom meeting details please [register to attend here](https://qut.zoom.us/meeting/register/tZEvcOqrrjkvHNH2ZqG5yed7Gh15Rp19Vatm).

**More Details**: The [QUT Digital Observatory website](https://research.qut.edu.au/digitalobservatory/office-hours/).
