---
title: "UQRUG"
subtitle: "The University of Queensland R Users Group"
title-block-banner: "#51247a"

about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/UQ_RUG
    - icon: file-earmark-text
      href: https://frama.link/uqrug
      text: Collaborative Document
    - icon: github
      text: Github
      href: https://github.com/uqlibrary/technology-training

---

<style>
#quarto-content{
margin-top: -205px;
padding-top: 175px; 
}
</style>


Welcome to the UQRUG monthly meetup!

### Who are we?

This is a **gathering for R users of all skills**, to help each other solve problems, to share resources and tips, and to simply hang out with a nice community.

### When do we meet?

We meet **every last Wednesday of the month** (12-2 pm, currently online and in person): sign up to the next event on the [Library training page](https://web.library.uq.edu.au/library-services/training)

You can also reach out any other time on [**chat.uq.edu.au**](https://chat.uq.edu.au/element/#/room/#uqrug:chat.uq.edu.au)


### Who can attend?
Anyone who wants to learn or share their knowledge are welcome to attend UQRUG.

### How do I get the Zoom link?

If you have a UQ affiliated account, you can sign up to the next event on the [Library training page](https://web.library.uq.edu.au/library-services/training)
Otherwise you can email the UQ Library training team for more help: training@library.uq.edu.au
