---
title: UQRUG 48
date: '2024-03-27'
description: '**Overview**: Identify Data Problems using visdat. <br /> **Questions**: GLMM Help, two y-axis plot, ggplot, splitting data into hours'
categories: meeting
toc: true
toc-depth: 5
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval= FALSE)
library(tidyverse)

```

## 2024-03-27: UQRUG 48

### R Overview of the Month

This month at UQRUG, before we jump into our help session for everyone to ask questions, this month Nick will look at how we can use some preliminary exploratory data visualisations to identify data issues using the [visdat](https://docs.ropensci.org/visdat/) package.

You can <a href="/presentations/24-03-visdat/visdat_overview.R" download>download the R file here</a> and then convert it to Rmd after downloading.

### Attendees
Add your name, where you're from, and why you're here:

| Name | Where are you from? | What brings you here? |
|--------|--------|--------|
| Nicholas Wiggins | UQ Library | Here to help! |
|Bel|QAEHS|Here to learn|
|Zoe MacLean|HASS Research Assistant|Hang out while coding|
|Luke Gaiter|Library|Here to learn/help/hangout|
|Christopher Sexton|Poche|Learn and improve R coding|
|Pia Wohland|SENV/HABS|Learn and help if Ican|
|Kar Ng|Senior Analyst Bank of Queensland | Hangout|
|Grant Taylor|HAB|Learn and Improve in R|
|David Green|UQ RCC|To help and to learn :-) |
|David Chau|QAAFI|see how to use visdat|
|Julia Wood|HABS PhD Candidate|Learn and help if I can :)|

### Questions


#### Q1 - Julia Wood - Help with GLMM
Need to run some different statistical methods, and need resources on"

* Generalised Linear Mixed Effects Models
* Underdispersion in a binomial generalised mixed effect model

**Answers**

*  [Mixed Models with R](https://m-clark.github.io/mixed-models-with-R/introduction.html)
*  [LADAL Mixed-effects regression](https://ladal.edu.au/regression.html#2_Mixed-Effects_Regression)

---

#### Q2 - Nick - More resources for data checking
Nanair provides a deeper dive into the kinds of missing data that visdat can provide

**Answers**

*  https://github.com/njtierney/naniar

---


#### Q3 - Jayne - Plotting two lots of data on one graph and splitting by time

- regarding plotting of two lots of data on the one graph 
- plus splitting the graphs into smaller time lots

**Answers**

Plotting two y axes
*  reminds me of some data I had analyse ... correlating events with denser sets of points

* This site has details for plotting a ggplot2 graph with two y axes: https://r-graph-gallery.com/line-chart-dual-Y-axis-ggplot2.html

Splitting data by time
*  Create a new variable that gives a value to each “block” of time and create the facet wrap on that
*  Perhaps using the Lubridate function hour() to extract the hour into a new column

---
