---
title: UQRUG 57
draft: false
editor: visual
date: '2024-12-11'
description: '**Overview**: Cool but Useless end of year event + drop in session<br /> **Questions**: Getting started, UniProt and API'
categories: meeting
toc: true
toc-depth: 5
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval= FALSE)
```

## Topic: **Cool but Useless end of year event**

...

## Attendees

Add your name, where you're from, and why you're here:

| Name      | Where are you from? | What brings you here?            |
|-----------|---------------------|----------------------------------|
| Lina      |                     |                                  |
| Valentina |                     |                                  |
| Sam       |                     |                                  |
| Ashley    |                     |                                  |
| Song      |                     |                                  |
| Luke      | Library             | Here to submit an entry and help |
| Cameron   | Library / Physics   | Here to submit an entry and help |
| David     | Library             | Here to submit an entry and help |
| Stéphane  | Library             | Here to submit an entry and help |

Competition entries

-   Luke's "NY Times headline scrape"

    -   Votes: 4

-   Cameron's "Christmas wrapping"

    -   Votes: 5

-   David's "haiku generator"

    -   Votes: 5

-   Steph's "Rudolph's ball of yarn"

    -   Votes: 4

## Questions and shared resources

-   Getting started with R:

    -   Install R: <https://cran.r-project.org/>

    -   Install RStudio: <https://posit.co/download/rstudio-desktop/>

    -   Start coding!

    -   Find relevant packages:

        -   Task Views: <https://cran.r-project.org/web/views/> (as a starting point)

        -   Online search

-   Joining data from UniProt based on pathway similarity

    -   could download tables, or

    -   could use API directly: <https://www.uniprot.org/help/programmatic_access>

        -   with httr2 package: <https://cran.r-project.org/web/packages/httr2/index.html>

    -   or could use an existing package to query the database: <https://cran.r-project.org/web/packages/UniprotR/index.html>

        -   note that some dependencies come from Bioconductor: <https://www.bioconductor.org/>

Resources shared during the meeting.

-   Cool but Useless' Mastodon: [https://fosstodon.org/\@coolbutuseless](https://fosstodon.org/@coolbutuseless)

    -   Their GitHub: <https://github.com/coolbutuseless/>

<!-- -->

-   Gallery of ggplot2 extensions: <https://exts.ggplot2.tidyverse.org/gallery/>
